@uri = {{$dotenv uri}}
@token = {{$dotenv token}}
@route = combustivel
@path = {{uri}}/{{route}}
@id = 615873326ec3ae9ce1e938ae

### [x] Create
post {{path}}/
content-type: application/json
Authorization: Bearer {{token}}

{
"date": "2021-01-01",
		"price": 6.56,
		"gas_type": "gasolina_comum",
		"volume": 10.0,
"observation": "teste2"
}
### [x] Read all
get {{path}}/
Authorization: Bearer {{token}}

### [x] Read id
get {{path}}/{{id}}
Authorization: Bearer {{token}}

### [x] Update
PATCH {{path}}/{{id}}
Authorization: Bearer {{token}}
content-type: application/json

{
  "date": "2021-01-01T00:00:00.000Z",
  "price": 6.56,
  "gas_type": "gasolina comum",
  "volume": 10,
  "observation": "teste2"
}

### [x] Delete
DELETE {{path}}/{{id}}
Authorization: Bearer {{token}}

