@uri = {{$dotenv uri}}
@token = {{$dotenv token}}
@route = km
@path = {{uri}}/{{route}}
@id = 6155cb9f66dca8b0a27acd32

### [x] Create
post {{path}}/
content-type: application/json
Authorization: Bearer {{token}}

{
  "date": "2021-01-01",
		"km": 10000,
		"observation": "teste"
}
### [x] Read all
get {{path}}/
Authorization: Bearer {{token}}

### [x] Read id
get {{path}}/{{id}}
Authorization: Bearer {{token}}

### [x] Update
PATCH {{path}}/{{id}}
Authorization: Bearer {{token}}
content-type: application/json

{
  "date": "2021-01-01",
		"km": 15000,
		"observation": "teste"
}

### [x] Delete
DELETE {{path}}/{{id}}
Authorization: Bearer {{token}}

