@uri = {{$dotenv uri}}
@token = {{$dotenv token}}
@route = manutencao
@path = {{uri}}/{{route}}
@id = 61a92557aba64a37a7f6dba3

### [x] Create
post {{path}}/
content-type: application/json
Authorization: Bearer {{token}}

{
		"date": "2021-01-01",
		//"service": "Troca de peca",
		"category": "peca",
        "service":"manutencao",
		"price": 200.00,
		"observation": "test12"
}

// precisa aparecer bad request quando nao enviar um dado obrigatorio

### [x] Read all
get {{path}}/
Authorization: Bearer {{token}}

### [x] Read id
get {{path}}/{{id}}
Authorization: Bearer {{token}}

### [x] Update
PATCH {{path}}/{{id}}
Authorization: Bearer {{token}}
content-type: application/json

{
		"date": "2021-01-01",
		"service": "Troca de peca",
		"category": "peca",
		"price": 210.00,
		"observation": "test12"
}

### [x] Delete
DELETE {{path}}/{{id}}
Authorization: Bearer {{token}}

