@uri = {{$dotenv uri}}
@token = {{$dotenv token}}
@route = pressao
@path = {{uri}}/{{route}}
@id = 616ab629edb0ae6d277e541d

### [x] Create
post {{path}}/
content-type: application/json
Authorization: Bearer {{token}}

{
  "position": "fl",
  "pressure_old": 10,
  "pressure_new":30,
  "observation":"teste"
}
### [x] Read all
get {{path}}/
Authorization: Bearer {{token}}

### [x] Read id
get {{path}}/{{id}}
Authorization: Bearer {{token}}

### [x] Update
PATCH {{path}}/{{id}}
Authorization: Bearer {{token}}
content-type: application/json

{
  "position": "fd",
  "pressure": 23
}

### [x] Delete
DELETE {{path}}/{{id}}
Authorization: Bearer {{token}}

