@uri = {{$dotenv uri}}
@id = 1

### Signup
post {{uri}}/user/signup
content-type: application/json

{
  "email": "test4@test.com",
  "password": "teste"
}

### Login
POST {{uri}}/user/login
content-type: application/json

{
  "email": "test4@test.com",
  "password": "teste"
}
### Delete
delete {{uri}}/user/{{id}}


