@uri = http://localhost:3000
@route = pressao
@path = {{uri}}/{{route}}
@id = 6155cb9f66dca8b0a27acd32
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VySWQiOiI2MTRkNDczNmUzNDE2OTkzZTY5ZTA5OWIiLCJpYXQiOjE2MzM1NzM5NjAsImV4cCI6MTYzMzU3NzU2MH0.XTer5Y4ets_lP5g2HpSaIpeDfuRkoWwOpeCnrE44oRU

### [x] Create
post {{path}}/
content-type: application/json
Authorization: Bearer {{token}}

{
  "position": "fd",
  "pressure": 33,
  "observation":"teste"
}
### [x] Read all
get {{path}}/
Authorization: Bearer {{token}}

### [x] Read id
get {{path}}/{{id}}
Authorization: Bearer {{token}}

### [x] Update
PATCH {{path}}/{{id}}
Authorization: Bearer {{token}}
content-type: application/json

{
  "position": "fd",
  "pressure": 23
}

### [x] Delete
DELETE {{path}}/{{id}}
Authorization: Bearer {{token}}

