@uri = http://localhost:3000
@route = pressao
@path = {{uri}}/{{route}}
@id = 6155cba766dca8b0a27acd34
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q0QHRlc3QuY29tIiwidXNlcklkIjoiNjE1Zjk2MjMxYWVlMmE5Y2RhMWRmODQyIiwiaWF0IjoxNjMzNjU0MzEzLCJleHAiOjE2MzM2NTc5MTN9.8e6EsOQab8sGMYQ2KrKfwBygWHC06qt0PeDW2Jfzb6I

### [x] Create
post {{path}}/
content-type: application/json
Authorization: Bearer {{token}}

{
  "position": "fr",
  "pressure": 33,
  "observation":"teste"
}
### [x] Read all
get {{path}}/
Authorization: Bearer {{token}}

### [x] Read id
get {{path}}/{{id}}
Authorization: Bearer {{token}}

### [x] Update
PATCH {{path}}/{{id}}
Authorization: Bearer {{token}}
content-type: application/json

{
  "position": "bl",
  "pressure": 23
}

### [x] Delete
DELETE {{path}}/{{id}}
Authorization: Bearer {{token}}

