@uri = https://herbie-21.herokuapp.com
@route = combustivel
@path = {{uri}}/{{route}}
@id = 615873326ec3ae9ce1e938ae
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VySWQiOiI2MTRkNDczNmUzNDE2OTkzZTY5ZTA5OWIiLCJpYXQiOjE2MzMxODMzMjUsImV4cCI6MTYzMzE4NjkyNX0.tUQt-qvOk0iNvUr67Wlff1io954-S6j7tggFQeUN8pA

### [x] Create
post {{path}}/
content-type: application/json
Authorization: Bearer {{token}}

{
"date": "2021-01-01",
		"price": 6.56,
		"gas_type": "gasolina comum",
		"volume": 10.0,
		"km": 1000.0,
"observation": "teste2"
}
### [x] Read all
get {{path}}/
Authorization: Bearer {{token}}

### [x] Read id
get {{path}}/{{id}}
Authorization: Bearer {{token}}

### [x] Update
PATCH {{path}}/{{id}}
Authorization: Bearer {{token}}
content-type: application/json

{
  "date": "2021-01-01T00:00:00.000Z",
  "price": 6.56,
  "gas_type": "gasolina comum",
  "volume": 10,
  "km": 12000,
  "observation": "teste2"
}

### [x] Delete
DELETE {{path}}/{{id}}
Authorization: Bearer {{token}}

