@uri = https://herbie-21.herokuapp.com
@id = 1

### Signup
post {{uri}}/user/signup
content-type: application/json

{
  "email": "test3@test.com",
  "password": "teste"
}

### Login
POST {{uri}}/user/login
content-type: application/json

{
  "email": "test@test.com",
  "password": "teste"
}
### Delete
delete {{uri}}/user/{{id}}
